Add New CSS Handles in QuantityStepper
vtex-apps/product-list pull request #108
Opened 2021-07-12 19:37 UTC by FabioWill

#### What problem is this solving?

Customize the QuantityStepper buttons and input with CSS Handles.

#### How to test it?

[Workspace](https://fabiowill--dentalpartner.myvtex.com/)

#### Screenshots or example usage:

Before:
![Screen Shot 2021-07-12 at 16 25 23](https://user-images.githubusercontent.com/6069644/125344906-4163ea80-e32e-11eb-9997-6dc7568be443.png)

After:
![Screen Shot 2021-07-12 at 16 25 35](https://user-images.githubusercontent.com/6069644/125345268-b6cfbb00-e32e-11eb-9e30-48b6d2b535dc.png)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![https://giphy.com/gifs/memecandy-LmNwrBhejkK9EFP504]

2021-07-15 12:49 UTC, FabioWill commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2021-07-19 19:11 UTC, victorhmp requested changes
Thanks for the PR @FabioWill! Left a few suggestions :)
Also, please update the CHANGELOG file.

2021-07-19 19:11 UTC, victorhmp commented on docs/README.md
> +| `quantitySelectorWrap`               |
```suggestion
| `quantitySelectorWrapper`               |
```

2021-07-19 19:11 UTC, victorhmp commented on react/components/QuantityStepper.tsx
> +    <div className={classnames(handles.quantitySelectorWrap, 'flex')}>
```suggestion
    <div className={`flex ${handles.quantitySelectorWrapper}`}>
```

2021-07-19 19:11 UTC, victorhmp commented on react/components/QuantityStepper.tsx
> +  'quantitySelectorWrap',
```suggestion
  'quantitySelectorWrapper',
```

2021-07-23 16:26 UTC, victorhmp approved these changes
LGTM, but please update the CHANGELOG with the suggestion I left :)

2021-07-23 16:26 UTC, victorhmp commented on CHANGELOG.md
> +
```suggestion
## [Unreleased]
### Added
- CSS Handles in QuantityStepper

```

2021-07-26 18:38 UTC, icazevedo approved these changes

2021-07-28 03:59 UTC, GonzaloVicens commented
Can someone provide information about when this modifications are going to be merged? We are in need of these CSS Handles for a company project. 
Thanks!

2021-07-28 12:50 UTC, merged