Add internationalization for remove button title attribute
vtex-apps/product-list pull request #146
Opened 2023-01-20 10:59 UTC by SpanacheNarcis

#### What problem is this solving?

We need the possibility of changing the title attribute on remove button 

#### How to test it?

Enter the link, add to cart a product, open the minicart, keep your mouse over the delete button. It will be "sterge" for RO. previous was "delete"

[nminicart](https://nminicart--iviteb.myvtex.com/)

#### Screenshots or example usage:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/43211787/213678322-b7f52723-abf2-472f-b87a-27b14ff19359.png">

<img width="405" alt="image" src="https://user-images.githubusercontent.com/43211787/213678475-9ac295bf-c28c-48df-b059-4982a9d4db72.png">

2023-01-20 11:15 UTC, mihainutiu-vtex commented
@SpanacheNarcis I published a beta version so you can install on the client until this PR is validated and approved.

`vtex.product-list@0.36.1-beta.0`

2023-01-23 12:42 UTC, sheilagomes requested changes

2023-01-23 12:42 UTC, sheilagomes commented on messages/ro.json
> +    "store/product-list.removeButton.titleAttribute": "sterge"
```suggestion
    "store/product-list.removeButton.titleAttribute": "înlătură"
```

2023-01-26 14:12 UTC, sheilagomes approved these changes
LGTM

2024-08-26 17:35 UTC, closed without merging