Replaces loading spinner by skeleton
vtex-apps/product-list pull request #24
Opened 2019-10-25 17:11 UTC by jeffersontuc

#### What problem is this solving?

This PR adds a preview skeleton to `product-list` in order to replace the current loading spinner on `checkout-cart`.

#### How should this be manually tested?

- Go to [Workspace](https://cartske--vtexgame1.myvtex.com/cart)
- Open your browser dev tools and change from 'No throttling' to 'Slow 3G' (optional)
- Verify if the skeleton is showed properly

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [x] [Linked this PR to a Clubhouse story (if applicable).](https://app.clubhouse.io/vtex/story/24408/aplicar-o-skeleton-no-carregamento-do-carrinho)
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

![image](https://user-images.githubusercontent.com/12574426/67590113-85fdbb80-f730-11e9-9890-9f009d2e1eb5.png)

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️| New feature 
_ | Breaking change 
_ | Technical improvements

2019-10-25 17:22 UTC, jeffersontuc commented
Tests are failing. I'm checking it!

2019-10-25 17:37 UTC, marcoskwkm requested changes

2019-10-25 17:37 UTC, marcoskwkm commented on react/AvailabilityMessage.tsx
> +  const { loading } = useOrderForm()
As we talked, `product-list` should not depend on our orchestrators. Especially now that the Store Framework team is going to use our components. It's better to receive `loading` as prop and pass it down.

2019-10-28 14:53 UTC, marcoskwkm requested changes

2019-10-28 14:53 UTC, marcoskwkm commented on react/ProductList.tsx
> +          loading: loading,
```suggestion
          loading,
```

2019-10-28 17:50 UTC, marcoskwkm approved these changes

2019-10-30 18:33 UTC, merged