Add advanced blocks configuration section to README
vtex-apps/product-list pull request #42
Opened 2020-01-28 17:39 UTC by victorhmp

#### What problem is this solving?

#### How should this be manually tested?

[Workspace](url)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-01-28 18:35 UTC, iaronaraujo requested changes

2020-01-28 18:35 UTC, iaronaraujo commented on CHANGELOG.md
> +- ### Added
```suggestion
### Added
```

2020-01-28 18:35 UTC, iaronaraujo commented on docs/README.md
> +The `product-list` block is made up of other smalled blocks. Currently, its default implementation is as follows (props omited):
```suggestion
The `product-list` block is made up of other smaller blocks. Currently, its default implementation is as follows (props omitted):
```

2020-01-28 18:38 UTC, iaronaraujo approved these changes

2020-01-28 18:51 UTC, omninando approved these changes

2020-01-29 02:06 UTC, guerreirobeatriz approved these changes

2020-01-29 14:24 UTC, merged